### ISSUE TITLE
Motor stays stalled after stalling it manually

### ISSUE THREAD

**Issue by laurensvalk** [ev3dev/lms2012-compat#50] opened 2017-01-02 18:44 UTC
![motorstop](https://cloud.githubusercontent.com/assets/12326241/21594505/a0f2f846-d123-11e6-8a78-3e3ed8fc4f76.png)

When running this program, the motor should keep on rotating, even after I force it to slow it down all the way to standstill manually.

But after I let go, the motor remains stalled.

Observed with a clean 4.9.0-ev3dev-bpo-stretch-r2-ev3-lms2012 image,  FW V1.99C.

**Comment by dlech** [comment] 2017-01-03 23:49
Fix has been released in kernel 4.9.0-ev3dev-bpo-stretch-r3-ev3-lms2012

Really, this is a duplicate of #48, just a different symptom.

**Closed as completed by dlech** 2017-01-03 23:49 UTC
Labels: bug
